name: geosentinel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - fastapi=0.112.0
  - uvicorn=0.30.6
  - pydantic=2.8.2
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - joblib=1.4.2
  - python-dateutil=2.9.0.post0
  - pyarrow=16.1.0
  - uvloop=0.19.0
  - httptools=0.6.1
  - websockets=12.0
  - watchfiles=0.21.0
  - matplotlib # notebook/plot için
  - ipykernel # jupyter kernel kaydı için
  - pip
  - pip:
      # - kagglehub==0.2.5  # istersen aç
