name: locate
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - fastapi=0.112.0
  - uvicorn=0.30.6
  - pydantic=2.8.2
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - joblib=1.4.2
  - python-dateutil=2.9.0.post0
  # Parquet okuma için:
  - pyarrow=16.1.0
  # Uvicorn performans opsiyonelleri:
  - uvloop=0.19.0
  - httptools=0.6.1
  - websockets=12.0
  - watchfiles=0.21.0
  # pip yalnızca gerektiğinde
  - pip
  - pip:
      # (Opsiyonel) DB setini Kaggle'dan çekeceksen aç:
      # - kagglehub==0.2.5
