# environment.yml
# Bu dosya conda ortamı kurmak için kullanılır.
# Komut: conda env create -f environment.yml
# Conda-forge kanal öncelikli yapılandırma içerir.

name: geosentinel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - fastapi=0.111.0
  - uvicorn=0.30.1
  - pydantic=2.8.2
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - joblib=1.4.2
  - python-dateutil=2.9.0.post0
  - pyarrow=16.1.0
  - shapely=2.0.4
  - haversine=2.8.1

  # Opsiyonel performans bileşenleri
  - uvloop=0.19.0
  - httptools=0.6.1
  - websockets=12.0
  - watchfiles=0.21.0

  # Pip ile kurulacak paketler
  - pip
  - pip:
      - kagglehub==0.2.5
